# Generated by Django 6.0.4 on 2026-05-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='srno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
